### ISSUE TITLE
0.9.0 published to crates.io but not pushed to main

### ISSUE THREAD

**Issue by Arnavion** [ctz/ct-logs#9]
https://crates.io/crates/ct-logs/0.9.0 exists but this repo's `main` branch is still at https://github.com/ctz/ct-logs/commit/320adea63b7a62a4b8ef3ee85aeddb5869798de4 as of this moment.

I see you've pushed [a v0.9.0 tag](https://github.com/ctz/ct-logs/tree/v/0.9.0) for https://github.com/ctz/ct-logs/commit/ed73724045d490c652544633bee5411351cacdb7 but this is not in the `main` branch. (Maybe you did a `git push --tags` but forgot to do the regular `git push` ?)

**Comment by ctz** [comment]
Derp, yeah. Thanks for pointing that out!
